format = """ 
[](fg:color1)\
$os\
[](bg:color1 fg:color3)\
$username\
[](bg:color3 fg:color5)\
$directory\
[ ](fg:color5)\
$git_branch\
$git_status\
$all\
$character"""

palette = 'colors'

[palettes.colors]
color1 = '{{ colors.primary.default.hex | auto_lightness:15 }}'
color2 = '{{ colors.on_primary_fixed_variant.default.hex | set_lightness:45 }}'
color3 = '{{ colors.secondary.default.hex | set_lightness:45 | set_saturation:45 }}'
color4 = '{{ colors.on_secondary_fixed_variant.default.hex }}'
color5 = '{{ colors.tertiary.default.hex | auto_lightness:15 }}'
color6 = '{{ colors.on_tertiary_fixed_variant.default.hex }}'
color7 = '{{ colors.on_surface_variant.default.hex | auto_lightness:15 }}'
color8 = '{{ colors.inverse_primary.default.hex }}'
color9 = '{{ colors.on_error.default.hex | auto_lightness:35}}'

[username]
show_always = true
format = '[$user ](bg:color3 fg:black)'
disabled = false

[os]
disabled = false
style = 'bg:color1 fg:black'
[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CachyOS = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
Nobara = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "

[cmd_duration]
format = "[$duration](fg:color3)"

[directory]
format = "[$path](bg:color5 fg:black)"
truncation_length = 2
truncation_symbol = "…/"

[character]
success_symbol = "[](bold color5)"
error_symbol = "[✗](bold color9)"
disabled = false

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Scripts" = "󰲋 "

[fossil_branch]
symbol = "  "
format = '[$symbol($version)]($style)'

[git_branch]
symbol = "  "
format = '[$symbol($branch) ($version)]($style)'
style = 'fg:color5'

[git_commit]
tag_symbol = '  '
format = '[$symbol($version)]($style)'
style = 'fg:color2'

[aws]
symbol = "   "
format = '[$symbol($version)]($style)'

[buf]
symbol = "  "
format = '[$symbol($version)]($style)'

[c]
symbol = "  "
format = '[$symbol($version)]($style)'

[cmake]
symbol = "  "
format = '[$symbol($version)]($style)'

[conda]
symbol = "  "
format = '[$symbol($version)]($style)'

[crystal]
symbol = "  "
format = '[$symbol($version)]($style)'

[dart]
symbol = "  "
format = '[$symbol($version)]($style)'

[docker_context]
symbol = "  "
format = '[$symbol($version)]($style)'

[elixir]
symbol = "  "
format = '[$symbol($version)]($style)'

[elm]
symbol = "  "
format = '[$symbol($version)]($style)'

[fennel]
symbol = "  "
format = '[$symbol($version)]($style)'

[golang]
symbol = "  "
format = '[$symbol($version)]($style)'

[guix_shell]
symbol = "   "
format = '[$symbol($version)]($style)'

[haskell]
symbol = "  "
format = '[$symbol($version)]($style)'

[haxe]
symbol = "  "
format = '[$symbol($version)]($style)'

[hg_branch]
symbol = "  "
format = '[$symbol($version)]($style)'

[hostname]
ssh_symbol = "  "
format = '[$symbol($version)]($style)'

[java]
symbol = "  "
format = '[$symbol($version)]($style)'

[julia]
symbol = "  "
format = '[$symbol($version)]($style)'

[kotlin]
symbol = "  "
format = '[$symbol($version)]($style)'

[lua]
symbol = "  "
format = '[$symbol($version)]($style)'

[memory_usage]
symbol = " 󰍛 "
format = '[$symbol($version)]($style)'

[meson]
symbol = " 󰔷 "
format = '[$symbol($version)]($style)'

[nim]
symbol = " 󰆥 "
format = '[$symbol($version)]($style)'

[nix_shell]
symbol = "  "
format = '[$symbol($version)]($style)'

[nodejs]
symbol = "  "
format = '[$symbol($version)]($style)'

[ocaml]
symbol = "  "
format = '[$symbol($version)]($style)'

[package]
symbol = " 󰏗 "
format = '[$symbol($version)]($style)'

[perl]
symbol = "  "
format = '[$symbol($version)]($style)'

[php]
symbol = "  "
format = '[$symbol($version)]($style)'

[pijul_channel]
symbol = "  "
format = '[$symbol($version)]($style)'

[python]
symbol = "  "
format = '[$symbol($version)]($style)'

[rlang]
symbol = " 󰟔 "
format = '[$symbol($version)]($style)'

[ruby]
symbol = "  "
format = '[$symbol($version)]($style)'

[rust]
symbol = " 󱘗 "
format = '[$symbol($version)]($style)'

[scala]
symbol = "  "
format = '[$symbol($version)]($style)'

[swift]
symbol = "  "
format = '[$symbol($version)]($style)'

[zig]
symbol = "  "
format = '[$symbol($version)]($style)'

[gradle]
symbol = "  "
format = '[$symbol($version)]($style)'
