format = """
[](color6)\
$os\
$username\
[](fg:color6 bg:color5 )\
$directory\
[](fg:color5 bg:color4)\
$git_branch\
$git_status\
[](fg:color4 bg:color3)\
$c\
$cpp\
$rust\
$golang\
$nodejs\
$php\
$java\
$kotlin\
$haskell\
$python\
[](fg:color3 bg:color2)\
$docker_context\
$conda\
$pixi\
[](fg:color2 bg:color1)\
$time\
[ ](fg:color1)\
$line_break$character"""

palette = 'colors'

[palettes.colors]
color1 = '{{ colors.primary.default.hex | auto_lightness:10 }}'
color2 = '{{ colors.on_primary_fixed_variant.default.hex | auto_lightness:25 }}'
color3 = '{{ colors.secondary.default.hex | set_lightness:45 | set_saturation:45 }}'
color4 = '{{ colors.on_secondary_fixed_variant.default.hex | auto_lightness:25 }}'
color5 = '{{ colors.tertiary.default.hex | auto_lightness:15 }}'
color6 = '{{ colors.on_tertiary_fixed_variant.default.hex | auto_lightness:15 }}'
color7 = '{{ colors.on_surface_variant.default.hex | auto_lightness:15 }}'
color8 = '{{ colors.inverse_primary.default.hex }}'
color9 = '{{ colors.on_error.default.hex | auto_lightness:35}}'

[os]
disabled = false
style = "bg:color6 fg:black"

[os.symbols]
Windows = "󰍲"
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
AOSC = ""
Arch = "󰣇"
Artix = "󰣇"
EndeavourOS = ""
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"
Pop = ""

[username]
show_always = true
style_user = "bg:color6 fg:black"
style_root = "bg:color6 fg:color9"
format = '[ $user ]($style)'

[directory]
style = "fg:black bg:color5"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = "󰝚 "
"Pictures" = " "
"Developer" = "󰲋 "

[git_branch]
symbol = ""
style = "bg:color4"
format = '[[ $symbol $branch ](fg:black bg:color4)]($style)'

[git_status]
style = "bg:color4"
format = '[[($all_status$ahead_behind )](fg:black bg:color4)]($style)'

[nodejs]
symbol = ""
style = "bg:color3"
format = '[[ $symbol( $version) ](fg:black bg:color3)]($style)'

[c]
symbol = " "
style = "bg:color3"
format = '[[ $symbol( $version) ](fg:black bg:color3)]($style)'

[cpp]
symbol = " "
style = "bg:color3"
format = '[[ $symbol( $version) ](fg:black bg:color3)]($style)'

[rust]
symbol = ""
style = "bg:color3"
format = '[[ $symbol( $version) ](fg:black bg:color3)]($style)'

[golang]
symbol = ""
style = "bg:color3"
format = '[[ $symbol( $version) ](fg:black bg:color3)]($style)'

[php]
symbol = ""
style = "bg:color3"
format = '[[ $symbol( $version) ](fg:black bg:color3)]($style)'

[java]
symbol = ""
style = "bg:color3"
format = '[[ $symbol( $version) ](fg:black bg:color3)]($style)'

[kotlin]
symbol = ""
style = "bg:color3"
format = '[[ $symbol( $version) ](fg:black bg:color3)]($style)'

[haskell]
symbol = ""
style = "bg:color3"
format = '[[ $symbol( $version) ](fg:black bg:color3)]($style)'

[python]
symbol = ""
style = "bg:color3"
format = '[[ $symbol( $version) ](fg:black bg:color3)]($style)'

[docker_context]
symbol = ""
style = "bg:color2"
format = '[[ $symbol( $context) ](fg:#83a598 bg:color2)]($style)'

[conda]
style = "bg:color2"
format = '[[ $symbol( $environment) ](fg:#83a598 bg:color2)]($style)'

[pixi]
style = "bg:color2"
format = '[[ $symbol( $version)( $environment) ](fg:black bg:color2)]($style)'

[time]
disabled = false
time_format = "%-I:%M%P"
style = "bg:color1"
format = '[[  $time ](fg:black bg:color1)]($style)'

[line_break]
disabled = false

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[✗](bold fg:color9)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:color6)'
vimcmd_replace_symbol = '[](bold fg:color6)'
vimcmd_visual_symbol = '[](bold fg:color5)'